version: "3"
services:
  tg-to-email-bot:
    build: .
    restart: always
    volumes:
      - ./app:/app
    environment:
      API_TOKEN: "API_TOKEN"
      CHAT_ID: "CHAT_ID"
      MAILGUN_API_KEY: "MAILGUN_API_KEY"
      EMAIL_DOMAIN: "EMAIL_DOMAIN"
      LIST_ADDRESS: "LIST_ADDRESS"
